community_website_ogonnelloe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("summernote/", include("django_summernote.urls")),
    path("", include("community_update_blog.urls"), name="community_updates_urls"),
    path("accounts/", include("allauth.urls")),
    path("noticeboard/", include("noticeboard.urls"), name="noticeboard_urls"),
]

noticeboard/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.Noticeboard.as_view(), name='noticeboard'),
    path('add_notice/', views.AddNotice.as_view(), name='add_notice'),
    path('<pk>/delete/', views.DeleteNotice.as_view(), name='delete_notice'),
    path('<pk>/update/', views.UpdateNotice.as_view(), name='update_notice'),
    ]

community_update_blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.core.validators import MinLengthValidator

STATUS = ((0, "Draft"), (1, "Published"))


class CommunityUpdate(models.Model):

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="community_update"
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField(
        validators=[
            MinLengthValidator(200, "the field must contain at least 200 characters")
        ]
    )
    featured_image = CloudinaryField("image", default="placeholder")
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name="community_update_likes", blank=True
    )

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"Community update: {self.title}, Status: {self.status}, Author: {self.author}"

    def number_of_likes(self):
        return self.likes.count()


class CommunityUpdateComment(models.Model):

    post = models.ForeignKey(
        CommunityUpdate,
        on_delete=models.CASCADE,
        related_name="community_update_comment",
    )
    commenter = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    class Meta:

        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.commenter}"

noticeboard/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class Notice(models.Model):

    title = models.CharField(max_length=45)
    id = models.BigAutoField(primary_key=True)
    approved = models.BooleanField(default=False)
    creator = models.CharField(max_length=80)
    description = models.TextField()
    contact_number = models.CharField(max_length=25, blank=True)
    contact_email = models.EmailField(max_length=254)
    location = models.CharField(max_length=60, null=True)
    background_image = CloudinaryField("image", default="placeholder")
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        get_latest_by = "created_on"

    def __str__(self):
        return f"Notice title: {self.title}, Approved: {self.approved}, Contact email: {self.contact_email}"

noticeboard/forms.py
from .models import Notice
from django import forms


class NoticeForm(forms.ModelForm):
    # Telling CommentForm what model to use and what fields to show in form
    class Meta:
        model = Notice
        fields = (
            "title",
            "description",
            "contact_number",
            "contact_email",
            "location",
            "background_image",
        )

noticeboard/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from noticeboard.models import Notice
from django.views import generic, View
from django.views.generic.edit import DeleteView, UpdateView
from .forms import NoticeForm


class AddNotice(View):
    def get(self, request, *args, **kwargs):

        return render(
            request,
            "add_notice.html",
            {"notice_added": False, "notice_form": NoticeForm()},
        )

    def post(self, request, *args, **kwargs):

        notice_form = NoticeForm(data=request.POST)

        notice_form.save()

        if notice_form.is_valid():
            notice_form.instance.creator = request.user.username
            notice_form.save()
        else:
            notice_form = NoticeForm()
        return render(
            request,
            "add_notice.html",
            {"notice_added": True, "notice_form": NoticeForm()},
        )


class DeleteNotice(LoginRequiredMixin, DeleteView):

    model = Notice

    success_url = "/noticeboard"

    template_name = "notice_confirm_delete.html"


class UpdateNotice(LoginRequiredMixin, UpdateView):
    model = Notice
    fields = [
        "title",
        "description",
        "contact_number",
        "contact_email",
        "location",
        "background_image",
    ]
    template_name = "notice_update_form.html"
    success_url = "/noticeboard"
    context = {"notice_added": True}


class Noticeboard(generic.ListView):

    model = Notice
    queryset = Notice.objects.filter(approved=True).order_by("created_on")
    template_name = "noticeboard.html"
    paginate_by = 2

templates/add_notice.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}
        <div class="container align-items-center py-3">

            {% if notice_added %}
        <div class="alert alert-success" role="alert">
            Your notice is awaiting approval
        </div>
        {% endif %}

        {% if user.is_authenticated %}

        <form class="card p-3 bg-light col-md-7 mx-auto" action="{% url 'add_notice' %}" method="post">
            <div id="div_id_title" class="control-group mb-3">
                <label for="id_title" class="control-label requiredField form-label">Title<span class="asteriskField">*</span></label>
                <div class="controls">
                    <input type="text" name="title" maxlength="45" class="textinput textInput form-control" required="" id="id_title">
                </div>
            </div>
            <div id="div_id_description" class="control-group mb-3">
                <label for="id_description" class="control-label requiredField form-label">
                Description<span class="asteriskField">*</span></label>
                <div class="controls">
                    <textarea name="description" cols="40" rows="10" class="textarea form-control" required="" id="id_description"></textarea>
                </div>
            </div>
            <div id="div_id_contact_number" class="control-group mb-3">
                <label for="id_contact_number" class="control-label form-label">
                Contact number
            </label>
                <div class="controls">
                    <input type="text" name="contact_number" maxlength="25" class="textinput textInput form-control" id="id_contact_number">
                </div>
            </div>
            <div id="div_id_contact_email" class="control-group mb-3">
                <label for="id_contact_email" class="control-label requiredField form-label">
                Contact email<span class="asteriskField">*</span> </label>
                <div class="controls">
                    <input type="email" name="contact_email" maxlength="254" class="emailinput form-control" required="" id="id_contact_email">
                </div>
            </div>
            <div id="div_id_location" class="control-group mb-3">
                <label for="id_location" class="control-label requiredField form-label">
                Location<span class="asteriskField">*</span> </label>
                <div class="controls">
                    <input type="text" name="location" maxlength="60" class="textinput textInput form-control" required="" id="id_location">
                </div>
            </div>
            <div id="div_id_background_image" class="control-group mb-3">
                <label for="id_background_image" class="control-label requiredField form-label">
                Image<span class="asteriskField">*</span> </label>
                <div class="controls">
                    <input type="file" name="background_image" class="clearablefileinput form-control" id="id_background_image">
                </div>
            </div>
            {% csrf_token %}
            <button type="submit" class="btn">Submit</button>
        </form>

    {% else %}

    <p>500 page</p>

    {% endif %}
            </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--  CSS links  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!--  JS scripts  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/b83175b9a4.js" crossorigin="anonymous"></script>

    <title>Ogonnelloe</title>
    <link rel="icon" type="image/x-icon" href="/static/images/favicon.png">
</head>
<body>

<header>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #53D8FB;">
      <div class="container-fluid">
        <a class="navbar-brand" id="logo" href="{% url 'home' %}">Ogonnelloe</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
            <a class="nav-link" href="{% url 'community_update_list' %}">Community Updates</a>
            <a class="nav-link" href="{% url 'noticeboard' %}">Noticeboard</a>
            <hr class="dropdown-divider">
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a>
            {% else %}
              <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
              <a class="nav-link" href="{% url 'account_login' %}">Sign In</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

</header>

<main>
    {% block content %}
    <!--  Content Goes Here  -->
    {% endblock content %}
</main>

  <!-- Copyright -->
  <div class="text-center p-4">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://github.com/sean-meade?tab=repositories">Sean Meade</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

</body>
</html>

templates/community_update_detail.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}
<!-- Page content-->
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on {{ post.created_on }} by {{ post.author }}</div>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4">
                            {% if "placeholder" in update.featured_image.url %}
                            <img class="img-fluid rounded" src="{{ post.featured_image.url|add:".jpg" }}" alt="..." /></figure>
                            {% else %}
                            <img class="img-fluid rounded" src="{{ post.featured_image.url }}" alt="..." /></figure>
                            {% endif %}
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{ post.content | safe }}</p>
                        </section>
                        {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'community_update_like' post.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                        {% endif %}
                    </article>
                    <!-- Comments section-->

                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                {% if commented %}
                                    <div class="alert alert-success" role="alert">
                                        Your comment is awaiting approval
                                    </div>
                                {% else %}
                                    {% if user.is_authenticated %}
                                    <form method="post" class="mb-4">
                                        <div id="div_id_body" class="control-group">
                                            <label for="id_body" class="control-label requiredField form-label">
                                                    Comment:
                                            </label>
                                            <div class="controls">
                                                <textarea name="body" rows="3" class="textarea form-control" id="id_body"
                                                          placeholder="Join the discussion and leave a comment!">
                                                </textarea>
                                            </div>
                                        </div>
                                        {% csrf_token %}
                                        <button type="submit" class="btn">Submit</button>
                                    </form>
                                    {% else %}
                                        <div>Log in or Sign up to leave a comment.</div>
                                    {% endif %}
                                {% endif %}
                                <!-- Comment with nested comments-->
                                {% for comment in comments %}
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="ms-3">
                                        <div class="fw-bold">{{ comment.commenter }}</div>
                                        {{ comment.body }}
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
{% endblock %}

templates/community_update_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<h1 class="py-2">Community Updates</h1>

<div class="card-group">
        {% for update in object_list %}
        <div class="card m-4" style="width: 18rem;">
            {% if "placeholder" in update.featured_image.url %}
            <img src="{{ update.featured_image.url|add:".jpg" }}" class="card-img-top" alt="...">
            {% else %}
            <img src="{{ update.featured_image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <span class="badge update">Community Update</span>
            <div class="card-body">
                <h5 class="card-title">{{ update.title }}</h5>
                <p class="card-text">{{ update.content | slice:'0:500' | safe}} ...</p>
                <p class="card-text"><small class="text-muted">Created on: {{ update.created_on }}</small></p>
                <a href="{% url 'community_update_detail' slug=update.slug %}" class="btn update">Go somewhere</a>
            </div>
        </div>
        {% endfor %}
       </div>

    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}

</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

    <section id="hero-outer">
        <div id="hero-image"></div>
        <div id="cover-text">
            <h2>Welcome to Ogonnelloes' Community Website</h2>
        </div>
    </section>

    <div class="container my-3">
        <div class="row">
            <p class="fs-5 mb-4">Welcome to Ogonnelloe’s community website.Ogonnelloe is situated in a beautiful part of
            East Clare, beside Lough Derg and the Sliabh Bearnagh mountains and between the towns of Killaloe and
            Scariff. Ogonnelloe has a thriving community of approx 850 people.</p>
        </div>
        <div class="row">

            {% for update in recent_posts %}
            <div class="col-md-4 d-flex align-items-stretch">
                <div class="card">
                    <div class="card-body">
                        {% if "placeholder" in update.featured_image.url %}
                        <img src="{{ update.featured_image.url|add:".jpg" }}" class="card-img-top" alt="...">
                        {% else %}
                        <img src="{{ update.featured_image.url }}" class="card-img-top" alt="...">
                        {% endif %}
                        <span class="badge update">Community Update</span>
                        <div class="card-body">
                            <h5 class="card-title">{{ update.title }}</h5>
                            <p class="card-text">{{ update.content | slice:'0:500' | safe}} ...</p>
                            <p class="card-text"><small class="text-muted">Created on: {{ update.created_on }}</small></p>
                            <a href="{% url 'community_update_detail' slug=update.slug %}" class="btn update">Read More ...</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="card-group">

    </div>

{% endblock %}

templates/notice_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <form class="card p-3 bg-light col-md-7 mx-auto" method="post">
        {% csrf_token %}

<p>Are you sure you want to delete "{{ object.title }}"?</p>

    <input type="submit" value="Confirm">
</form>

{% endblock %}

templates/notice_update_form.html
{% extends "base.html" %}

{% block content %}
<div class="container align-items-center">

<form class="card p-3 bg-light col-md-7 mx-auto my-3" method="post" >
    {% csrf_token %}
    <p>
    <label class="form-label" for="id_title">Title:</label>
    <input class="form-control" type="text" name="title" value="Notice test add some text" maxlength="45" required="" id="id_title">
  </p>
  <p>
    <label class="form-label" for="id_description">Description:</label>
    <textarea class="textarea form-control" name="description" cols="40" rows="10" required="" id="id_description">This is a notice test with updated added text what am I missing here? Adding more text</textarea>
  </p>
  <p>
    <label class="form-label" for="id_contact_number">Contact number:</label>
    <input class="form-control" type="text" name="contact_number" value="3456789253" maxlength="25" id="id_contact_number">
  </p>
  <p>
    <label class="form-label" for="id_contact_email">Contact email:</label>
    <input class="form-control" type="email" name="contact_email" value="email@email1.com" maxlength="254" required="" id="id_contact_email">
  </p>
  <p>
    <label class="form-label" for="id_location">Location:</label>
    <input class="form-control" type="text" name="location" value="here" maxlength="60" required="" id="id_location">
  </p>
  <p>
    <label class="form-label" for="id_background_image">Image:</label>
    Currently: <a href="https://res.cloudinary.com/smeade/image/upload/placeholder">placeholder</a><br>
Change:
<input class="form-control" type="file" name="background_image" id="id_background_image">

  </p>
    <input class="btn" type="submit" value="Update">
    </form>
</div>

{% endblock %}

templates/noticeboard.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
    <h1 class="py-2">Noticeboard</h1>
        {% if user.is_authenticated %}
            <p><a href="{% url 'add_notice' %}" class="btn notice">Add Notice</a></p>
        {% endif %}
    {% if context.notice_added %}
        <div class="alert alert-success" role="alert">
            Your Notice is awaiting approval
        </div>
    {% endif %}

    <div class="row">
    {% for notice in object_list %}
    <div class="col-md-6 d-flex align-items-stretch">
        <div class="card">
            <div class="card-body">
                {% if "placeholder" in notice.background_image.url %}
                <img src="{{ notice.background_image.url|add:".jpg" }}" class="card-img-top" alt="...">
                {% else %}
                <img src="{{ notice.background_image.url }}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ notice.title }}</h5>
                    <p class="card-text">{{ notice.description| safe}}</p>
                    <p class="card-text"><small class="text-muted">Created on: {{ notice.created_on }}</small></p>
                    {% if notice.creator == user.username %}
                    <a href="{% url 'delete_notice' pk=notice.id %}" class="btn notice">Delete</a>
                    <a href="{% url 'update_notice' pk=notice.id %}" class="btn notice">Update</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    </div>

{% endblock %}